// Run from repository root with Node 24+. Install pinned dependencies in ./next-project-validation first.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
if (Number(process.versions.node.split('.')[0]) < 24) throw new Error('Node 24+ is required');
const require = createRequire(new URL('./next-project-validation/package.json', import.meta.url));
const ts = require('typescript');
const { JSDOM } = require('jsdom');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const sourcePath = '02-nextjs-frontend/basics/08-first-project.md';
const text = fs.readFileSync(path.join(root, sourcePath), 'utf8').replace(/\r\n/g, '\n');
const source = text.match(/```tsx\n([\s\S]*?)```/)[1];
const compiled = ts.transpileModule(source, {compilerOptions: {jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});
assert.equal(compiled.diagnostics.length, 0);
const dom = new JSDOM('<html><body></body></html>', {url:'http://localhost:3000'});
for (const k of ['window','document','HTMLElement','localStorage']) globalThis[k]=dom.window[k];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react');
const {render,screen,fireEvent,cleanup}=require('@testing-library/react');
const compiledModule={exports:{}};
new Function('require','module','exports',compiled.outputText)(require,compiledModule,compiledModule.exports);
const Drafts=compiledModule.exports.default;
const mount=()=>render(React.createElement(Drafts));
const read=()=>fireEvent.click(screen.getByText('读取已有草稿'));
const save=()=>fireEvent.click(screen.getByText('保存标题'));
const key='dev-quest-article-drafts-v1';
mount(); assert.equal(screen.getByText('保存标题').disabled,true); read(); assert.ok(screen.getByText('暂无草稿。'));
for(const title of ['A','B','   ']){fireEvent.change(screen.getByLabelText('文章标题'),{target:{value:title}});save();}
assert.deepEqual(JSON.parse(localStorage.getItem(key)),['A','B']);assert.ok(screen.getByText('标题不能为空。'));
cleanup();mount();read();assert.deepEqual(screen.getAllByRole('listitem').map(x=>x.textContent),['A','B']);
localStorage.setItem(key,'not-json');read();assert.equal(screen.getByText('保存标题').disabled,true);assert.equal(localStorage.getItem(key),'not-json');
localStorage.setItem(key,'["A","B"]');read();fireEvent.change(screen.getByLabelText('文章标题'),{target:{value:'C'}});
const original=dom.window.Storage.prototype.setItem;dom.window.Storage.prototype.setItem=()=>{throw new Error('quota')};save();
assert.equal(screen.getByLabelText('文章标题').value,'C');assert.deepEqual(screen.getAllByRole('listitem').map(x=>x.textContent),['A','B']);
dom.window.Storage.prototype.setItem=original;cleanup();dom.window.close();
const report={source:sourcePath,sourceBlockSha256:createHash('sha256').update(source).digest('hex'),status:'PASS',node:process.version,typescript:ts.version,react:React.version,cases:['TSX transpilation','read gate','empty state','A/B save','whitespace rejection','remount/read persistence','corrupt data preserved and save disabled','write failure preserves draft/list'],limits:'JSDOM DOM verification only; no TypeScript semantic check, Next.js build, hydration or real browser verification.'};
report.dependencyManifest = 'shared-resources/tools/document-quality/next-project-validation/package.json';
report.dependencyLock = 'shared-resources/tools/document-quality/next-project-validation/pnpm-lock.yaml';
fs.writeFileSync(path.join(root,'shared-resources/tools/document-quality/reports/next-first-project-2026-09-19.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
